# Copyright (C) 2011 by Michele Silva (michele.silva@gmail.com)
# This code is part of the Biopython distribution and governed by its
# license. Please see the LICENSE file that should have been included
# as part of this package.

""" Exceptions generated by the TorusDBN model and trainer. """

from Bio import BiopythonWarning


class TorusDBNException(Exception):
    """ General TorusDBN error. """
    
    
class TorusDBNBuildPolypeptideException(TorusDBNException):
    """ Can't build a list of Polypeptide objects. """
    
    
class TorusDBNChainBreakException(TorusDBNException):
    """ A chain break was detected and can't be handled. """
    

class TorusDBNWarning(BiopythonWarning):
    """ General TorusDBN warning. """
